controller_manager:
  ros__parameters:
    update_rate: 100        # Control loop frequency
    use_sim_time: true

    joint_state_broadcaster: # For publishing the state of the joint sensors
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

simple_velocity_controller:
  ros__parameters:
    joints:
     - wheel_left_joint
     - wheel_right_joint